### ISSUE TITLE
增加字段

### ISSUE THREAD

**Issue by syxhina** [keyuinfo/Database#1]
常量定义.md数据库中，家具/风格增加NORTHERN EUROPE | 5 | Integer | 北欧。
家具/材质增加CLOTH | 5 | Integer | 布料。LEATHERWEAR | 6 | Integer | 皮革。

**Comment by syxhina** [comment]
https://github.com/keyuinfo/Database/blob/master/%E5%B8%B8%E9%87%8F%E5%AE%9A%E4%B9%89.md

**Comment by morphinewan** [comment]
@cureee 前端js的常量你负责加一下
加好后，在assign给我，我来加后端和app
